server:
  port: 81

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: jdbc:mysql://localhost:3306/youBeMyCollegue?useSSL=false&allowPublicKeyRetrieval=true
    # DB username
    username: root
    # DB password
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true